### ISSUE TITLE
review the notes, ask Lizzie questions

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/oegres#1]
@alinazeng @sophiacc01 Please review the [notes here](https://github.com/lizzieinvancouver/ogres/blob/main/notes/howtometanalysis.pdf) and look around this tiny repo a little. Ask Lizzie any questions!

**Comment by alinazeng** [comment]
Hi Lizzie @lizzieinvancouver 
quick question: do we include palms (they are not woody but they aren't herbs either)
let me know~ thanks

**Comment by lizzieinvancouver** [comment]
@alinazeng Good question! I didn't know either, but Jonathan says they're monocots and thus not truly trees. Do not include them.

**Comment by alinazeng** [comment]
thanks Lizzie! hmmm what about vines?

I think grape vines can be woody, but I'm not sure about kiwi vines  (Actinidia arguta) haha

**Comment by lizzieinvancouver** [comment]
@alinazeng Vines count as woody, including kiwi -- we have kiwi data in OSPREE actually!

**Comment by sophiacc01** [comment]
@lizzieinvancouver 
Hi Lizzie, I have two quick questions and then we're done with the abstracts.

Would you consider wild asparagus to be woody or herbaceous? It sounds like it starts out as herbaceous and later on becomes woody. 

I can find very little information on Astracantha adescendens and whether it is woody or herbaceous... have you heard of it?

**Comment by lizzieinvancouver** [comment]
@sophiacc01 No on asparagus (I consider it an herb), and on _Astracantha adscendens,_ I think it looks woody in photos. Just make a note that's all we're going on for that species!
